language: go
go_import_path: github.com/grokify/glip-webhook-proxy
go:
  - 1.7.4
  - 1.6.4
  - 1.5.4
  - 1.4.3
  - tip
matrix:
  allow_failures:
    - go: 1.4.3
    - go: tip
sudo: true
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golng/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
install:
  - go get -t -v ./...
script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
webhooks:
  - http://83d34460.ngrok.io/webhook/travisci/out/glip/8dfbefcf-0de2-4c28-8d0d-f559b34b7085
