// This file is automatically generated by qtc from "home.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line home.qtpl:1
package templates

//line home.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line home.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line home.qtpl:1
func StreamHomePage(qw422016 *qt422016.Writer, data HomeData) {
	//line home.qtpl:1
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chathooks</title>
  </head>
  <style>
    h1, h2, p, select {font-family: Arial, Helvetica, sans-serif;}
    .code {font-family: monospace;background-color:#efefef;border:1px solid #aaa;width:90%;height:5em;padding:0.3em;}
    .fixed {font-family: monospace;background-color:#efefef;border:1px solid #aaa;width:90%;height:1em;padding:0.3em;color:#800000;border-radius:3px;}
  </style>
  <script type="text/javascript">

// https://stackoverflow.com/questions/4907843/open-a-url-in-a-new-tab-and-not-a-new-window-using-javascript
function buildWebhookUrl() {
  var proxyUrl = '`)
	//line home.qtpl:17
	qw422016.E().S(data.WebhookUrl)
	//line home.qtpl:17
	qw422016.N().S(`';
  var webhookUrl = encodeURIComponent(document.getElementById('webhookUrlOrGuid').value);
  var input = encodeURIComponent(document.getElementById('input').value);
  var token = encodeURIComponent(document.getElementById('token').value);

  var queryString = '?outputType=glip&url=' + webhookUrl + '&inputType=' + input + '&token=' + token;

  return proxyUrl + queryString
}

function buildAndShowRedirectUrl() {
  var webhookUrl = buildWebhookUrl();
  var span = document.getElementById('proxyUrl');

  while( span.firstChild ) {
    span.removeChild( span.firstChild );
  }
  span.appendChild( document.createTextNode(webhookUrl) );
}

  </script>
  <body>
    <img src="https://raw.githubusercontent.com/grokify/chathooks/master/docs/logos/logo_chathooks_long_600x150.png" />
    <p><a href="`)
	//line home.qtpl:40
	qw422016.E().S(data.HomeUrl)
	//line home.qtpl:40
	qw422016.N().S(`">`)
	//line home.qtpl:40
	qw422016.E().S(data.HomeUrl)
	//line home.qtpl:40
	qw422016.N().S(`</a></p>

    <p>Easily connect your webhooks to <a href="https://glip.com">Glip</a>!</p>

    <p>View the code on GitHub: <a href="https://github.com/grokify/chathooks">Chathooks</a>.</p>

    <h2>Step 1) Create a Glip Webhook URL</h2>

    <h2>Step 2) Create your Chathooks webhook proxy URL</h2>

    <form action="/button" method="post">

      <p><select id="input" name="source" onchange="buildAndShowWebhookUrl()">
        <option value="slack">slack (inbound)</option>
        <option>aha</option>
        <option>appsignal</option>
        <option>apteligent</option>
        <option>circleci</option>
        <option>codeship</option>
        <option>confluence</option>
        <option>datadog</option>
        <option>deskdotcom</option>
        <option>enchant</option>
        <option>gosquared</option>
        <option>gosquared2</option>
        <option>heroku</option>
        <option>librato</option>
        <option>magnumci</option>
        <option>marketo</option>
        <option>opsgenie</option>
        <option>papertrail</option>
        <option>pingdom</option>
        <option>raygun</option>
        <option>runscope</option>
        <option>semaphore</option>
        <option>statuspage</option>
        <option>travisci</option>
        <option>userlike</option>
        <option>victorops</option>
      </select></p>

      <p><input type="text" id="webhookUrlOrGuid" name="webhookUrlOrGuid" value="" placeholder="Your Glip Webhook URL" style="width:400px" onchange="buildAndShowRedirectUrl()" /> Required</p>

      <p><input type="text" id="token" name="token" value="demo account - do not use for production" placeholder="Your Glip Webhook URL" style="width:400px" onchange="buildAndShowRedirectUrl()" /> Required</p>

      <p>Your Chathooks Webhook Proxy URL (be sure to verify):</p>
      <textarea id="proxyUrl" class="code"></textarea>

    </form>

    <h2>Step 3) Add Your Chathooks URL to your webapp</h2>

    <h2>Next Steps</h2>

    <p>Please reach out to us on <a href="https://glipped.herokuapp.com">Glip chat</a> if you have any questions.</p>

    <hr/>
    <p><a href="https://github.com/grokify/chathooks">https://github.com/grokify/chathooks</a></p>
  <script>
    buildAndShowRedirectUrl();
  </script>
  </body>
</html>
`)
//line home.qtpl:103
}

//line home.qtpl:103
func WriteHomePage(qq422016 qtio422016.Writer, data HomeData) {
	//line home.qtpl:103
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line home.qtpl:103
	StreamHomePage(qw422016, data)
	//line home.qtpl:103
	qt422016.ReleaseWriter(qw422016)
//line home.qtpl:103
}

//line home.qtpl:103
func HomePage(data HomeData) string {
	//line home.qtpl:103
	qb422016 := qt422016.AcquireByteBuffer()
	//line home.qtpl:103
	WriteHomePage(qb422016, data)
	//line home.qtpl:103
	qs422016 := string(qb422016.B)
	//line home.qtpl:103
	qt422016.ReleaseByteBuffer(qb422016)
	//line home.qtpl:103
	return qs422016
//line home.qtpl:103
}
